server:
  port: 8080

spring:
  application:
    name: book-service
  datasource:
    url: jdbc:mysql://localhost:33061/book-service
    username: root
    password: MySQL@8118512
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com:
      netflix:
        eureka: DEBUG
        discovery: DEBUG